fix: Port 4000 is already occupied (#29)
Kanna727/jekyll-run pull request #47
Opened 2021-10-04 16:51 UTC by chriskyfung

- Stop Jekyll server before exiting VS Code within `deactivate()`.
- Enable user easily changes the port and the base URL configuration in the extension settings.
- Deprecated `openLocalJekyllSite()` in `open-in-browser.ts`
- Changed to get the server address (_including the **port** and **base URL**_) from stdout.
- Replaced `openLocalJekyllSite()` with `openUrl()`

2021-10-07 09:53 UTC, Kanna727 requested changes

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
> +export function deactivate() {
I think the ability to stop Jekyll server before exiting VS Code should be an option to users which can be set in the extension settings with default being false. Let me know your thoughts

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
> +    if (currWorkspace && isRunning) {
This code is duplicate of [Stop command](https://github.com/chriskyfung/jekyll-run/blob/master/src/extension.ts#L386). Please extract this into a separate function and use it at both the places

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
> +function checkConfigAndGetPort(currWorkspace: WorkspaceFolder): boolean {
```suggestion
function getPortAndBaseurl(currWorkspace: WorkspaceFolder): boolean {
```

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
>                  return checkConfigAndGetPort(currWorkspace);
```suggestion
                return getPortAndBaseurl(currWorkspace);
```

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
>              return checkConfigAndGetPort(currWorkspace);
```suggestion
            return getPortAndBaseurl(currWorkspace);
```

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
> +    };
```suggestion
```

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
> +        serverBaseurl = configInArgs.baseurl? baseurlInArgs : baseurlInConfig;
```suggestion
        getConfigFromArgs();
        serverPort = portInArgs || portInConfig;
        serverBaseurl = baseurlInArgs || baseurlInConfig;
```

2021-10-07 09:53 UTC, Kanna727 commented on src/cmds/run.ts
> +              this.address = match ? match[1] : `http://localhost:${serverPort}`;
```suggestion
              this.address = match?.[1]  || `http://localhost:${serverPort}`;
```

2021-10-07 09:53 UTC, Kanna727 commented on src/extension.ts
> +            openUrl(address);
Please change the default parameter value of [`openUrl`](https://github.com/chriskyfung/jekyll-run/blob/master/src/utils/open-in-browser.ts#L4) function to `http://127.0.0.1:4000`. Unfortunately, GitHub is not allowing me to comment on an unchanged line. Sorry for the inconvenience.

2021-10-07 10:10 UTC, Kanna727 commented
@chriskyfung Thanks a lot for the PR. Please complete the below tasks. Once done, I'll merge the PR.

- [ ] Do the review changes. Feel free to discuss.

2021-10-07 16:02 UTC, chriskyfung commented on src/extension.ts
> +export function deactivate() {
I think we can add an option in the extension settings but I prefer to stop Jekyll when exit VS Code. Otherwise, it is painful to restore the port and unable to monitor the Jekyll server in a new VS Code window.

I have no idea about why the Jekyll should continue to run in the background.

2021-10-07 16:04 UTC, chriskyfung commented on src/extension.ts
> +    if (currWorkspace && isRunning) {
Make sense!

2021-10-07 16:18 UTC, chriskyfung commented on src/extension.ts
> +export function deactivate() {
Can you suggest a name for the new extension setting? That I add it to the `deactivate()` and `package.json`.

2021-10-07 18:45 UTC, chriskyfung commented on src/extension.ts
> +    if (currWorkspace && isRunning) {
I changed to stop the server in `deactivate()` using the following code:

```ts
commands.executeCommand('jekyll-run.Stop');
```

I think it will be simpler and maintainable.

2021-10-07 18:52 UTC, chriskyfung commented on src/extension.ts
> +export function deactivate() {
I made a draft as belows:

```json
# package.json
"jekyll-run.stopServerOnExit": {
	"type": "boolean",
	"description": "Stop Jekyll server before exiting VS Code",
	"default": "false"
}
```

```ts
# extension.ts
export function deactivate() {
    const config = Config.get();
    if (config.stopServerOnExit) {
        console.log("Exit VSCode. Stopping: " + pid);
        commands.executeCommand('jekyll-run.Stop');
    }
}
```

2021-10-24 09:50 UTC, Kanna727 approved these changes

2021-10-24 09:50 UTC, Kanna727 commented on src/extension.ts
> +export function deactivate() {
Thanks @chriskyfung. Sometimes users might want just the extension to stop but not the server. So, let's provide this option for users to do whatever they want

2021-10-24 09:51 UTC, merged

2021-10-24 09:53 UTC, Kanna727 commented
Hi @chriskyfung, I forgot to mention but could you please submit another PR with updated README that explains the new config we've added?

2021-10-24 09:54 UTC, Kanna727 commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on [GitHub release](https://github.com/Kanna727/jekyll-run/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: